// package haserrors contains a function that is called "Foo".
package foofunc

func Foo() {} // This should fail foo_func_check
